#!/bin/bash

ARGS="--param ../Labs/rmi-2425/C4-config.xml"
ARGS+=" --lab ../Labs/rmi-2425/C4-lab.xml"
ARGS+=" --grid ../Labs/rmi-2425/C4-grid.xml"
ARGS+=" --scoring 3"
(cd simulator; ./simulator $ARGS) &

sleep 2

(cd Viewer; ./Viewer --autoconnect)&

sleep 3

(cd pClient; ./s4.sh)

killall simulator
killall Viewer

echo Bye
