#!/bin/bash

ARGS="--param ../Labs/rmi-2425/C2-config.xml"
ARGS+=" --lab ../Labs/rmi-2425/C2-lab.xml"
ARGS+=" --grid ../Labs/rmi-2425/C2-grid.xml"
ARGS+=" --scoring 2"
(cd simulator; ./simulator $ARGS) &

sleep 2

(cd Viewer; ./Viewer --autoconnect) &

sleep 3

(cd agent_102959_118485; ./run.sh -c 2)

# killall simulator
# killall Viewer

echo Bye
