#!/bin/bash

ARGS="--param ../Labs/rmi-2425/C4-config.xml"
ARGS+=" --lab ../Labs/rmi-2425/C4-lab.xml"
ARGS+=" --grid ../Labs/rmi-2425/C4-grid.xml"
ARGS+=" --scoring 3"
(cd simulator; ./simulator $ARGS) &

sleep 2

(cd Viewer; ./Viewer --autoconnect)&

sleep 3

# (cd pClient; python3 mainC4_G.py)
(cd pClient; python3 mainRob_C4.py)


(cd simulator; gawk -f mapping_score.awk planning.out ../pClient/map_created.map) &
(cd simulator; gawk -f mapping_score.awk planning.out planning.out) &

(cd simulator; gawk -f planning_score.awk planning.out ../pClient/path_created.path) &
(cd simulator; gawk -f planning_score.awk planning.out planning.out) &

killall simulator
killall Viewer

echo Bye
