#!/bin/bash

ARGS="--param ../Labs/rmi-2425/C3-config.xml"
ARGS+=" --lab ../Labs/rmi-2122/C3-lab.xml"
ARGS+=" --grid ../Labs/rmi-2122/C3-grid.xml"
ARGS+=" --scoring 3"
(cd simulator; ./simulator $ARGS) &

sleep 2

(cd Viewer; ./Viewer --autoconnect) &

sleep 3

(cd pClient; ./s3.sh)

killall simulator
killall Viewer


echo Bye
